/**
 * Client-side publication engine (§7.1 as respecified 2026-07-18, §13).
 *
 * 1-second tick loop. Each tick carries the full per-second quota (`rate`
 * messages) split into batches of at most `maxBatchSize`, fired concurrently
 * via Promise.allSettled. The first fan-out fires immediately at start; the
 * in-flight guard covers the whole fan-out, so ticks are skipped until the
 * previous fan-out settles.
 *
 * The engine holds no persistent state and is created fresh for each run. The
 * caller supplies the run identity ({@link RunIdentity}) — the generatorStore
 * owns it; the engine generates none of the ids. Progress and terminal outcomes are
 * reported through {@link EngineCallbacks}.
 */
import { message } from 'antd'
import type {
  RunConfig,
  RunSummary,
  RunStatus,
  PublishError,
} from '../types/generator'
import type { BatchMessageRequest, MessageRequest } from '../types/queue'
import { resolveString, resolveTemplate } from './templateResolver'
import type { TemplateContext } from './templateResolver'
import { publishBatch } from '../services/publishService'
import { useValueListStore } from '../stores/valueListStore'

/** Run identity, generated by generatorStore.startRun() and passed through (§11). */
export interface RunIdentity {
  runId: string
  correlationId: string
}

export interface EngineCallbacks {
  onTick(sent: number, errors: PublishError[], consecErrors: number, elapsedMs: number): void
  onComplete(summary: RunSummary): void
  onStop(summary: RunSummary): void
  onError(summary: RunSummary, reason: string): void
}

export interface PublicationEngine {
  start(config: RunConfig, identity: RunIdentity, callbacks: EngineCallbacks): void
  stop(): void
}

const TICK_MS = 1000

/** Extract an HTTP status code from a thrown publish error, if present. */
function httpStatusOf(error: unknown): number | undefined {
  const response = (error as { response?: { status?: number } })?.response
  return typeof response?.status === 'number' ? response.status : undefined
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

/** Create a new, single-use publication engine. */
export function createPublicationEngine(): PublicationEngine {
  let timer: ReturnType<typeof setInterval> | null = null
  let inFlight = false
  let finished = false
  // Set by stop() while a fan-out is in flight: the settle path processes the
  // acknowledged results FIRST, then reports STOPPED — the summary must never
  // understate real publishes (decision 2026-07-18, option a).
  let stopRequested = false

  let config: RunConfig
  let callbacks: EngineCallbacks
  let valueLists: Record<string, string[]>

  let runId: string
  let correlationId: string
  let startedAt = 0
  let nextMessageId = 1
  let sent = 0
  let consecErrors = 0
  const errors: PublishError[] = []

  function buildSummary(finalStatus: RunStatus): RunSummary {
    const durationMs = Date.now() - startedAt
    return {
      totalSent: sent,
      targetTotal: config.rate * config.durationSecs,
      avgRate: durationMs > 0 ? sent / (durationMs / 1000) : 0,
      durationMs,
      totalErrors: errors.length,
      finalStatus,
      runId,
      errors: [...errors],
    }
  }

  function clear(): void {
    if (timer !== null) {
      clearInterval(timer)
      timer = null
    }
  }

  /** One batch of `size` messages; ids are assigned sequentially across groups. */
  function buildBatch(size: number): { firstMessageId: number; request: BatchMessageRequest } {
    const { template } = config
    const firstMessageId = nextMessageId
    const messages: MessageRequest[] = []
    const now = new Date()
    for (let i = 0; i < size; i++) {
      const messageId = nextMessageId++
      const context: TemplateContext = {
        messageId,
        index: messageId - 1,
        runId,
        correlationId,
        now,
        valueLists,
      }
      const payload = resolveTemplate(template.payloadSchema, context)
      // §5.3: placeholders are valid in header values — resolved per message.
      const headers = Object.fromEntries(
        Object.entries(template.headers).map(([key, headerValue]) => [
          key,
          resolveString(headerValue, context),
        ])
      )
      messages.push({
        payload,
        headers,
        messageType: template.messageType,
        correlationId,
        priority: template.priority,
        delaySeconds: template.delaySeconds,
        messageGroup: template.messageGroup,
      })
    }
    return { firstMessageId, request: { messages, maxBatchSize: config.maxBatchSize } }
  }

  async function tick(): Promise<void> {
    if (finished || inFlight) return

    if (Date.now() - startedAt >= config.durationSecs * 1000) {
      finished = true
      clear()
      callbacks.onComplete(buildSummary('completed'))
      return
    }

    inFlight = true

    // The full per-second quota, split into groups of ≤ maxBatchSize.
    // Template resolution can THROW here (resolveTemplate surfaces authoring
    // errors via JSON.parse). A throw must terminate the run through onError —
    // an escaped exception from this async tick would be an unhandled
    // rejection, leaving the run stuck in RUNNING forever.
    const batches: Array<{ firstMessageId: number; request: BatchMessageRequest }> = []
    try {
      let remaining = Math.max(1, Math.floor(config.rate))
      while (remaining > 0) {
        const size = Math.min(config.maxBatchSize, remaining)
        batches.push(buildBatch(size))
        remaining -= size
      }
    } catch (error) {
      finished = true
      clear()
      inFlight = false
      callbacks.onError(
        buildSummary('error'),
        `Template failed to resolve: ${messageOf(error)}`
      )
      return
    }

    const settled = await Promise.allSettled(
      batches.map((b) => publishBatch(config.setupId, config.queueName, b.request))
    )

    // Process results in batch order: any success resets the streak (§6.1 rule
    // "resets on every successful batch response", preserved under concurrency).
    // This runs even when stop was requested mid-flight — acknowledged sends
    // belong in the summary.
    for (let i = 0; i < settled.length; i++) {
      const result = settled[i]
      if (result.status === 'fulfilled') {
        sent += result.value.messagesSent
        consecErrors = 0
      } else {
        consecErrors++
        errors.push({
          messageIndex: batches[i].firstMessageId,
          httpStatus: httpStatusOf(result.reason),
          message: messageOf(result.reason),
          timestamp: new Date().toISOString(),
        })
      }
    }
    inFlight = false

    // A stop requested mid-flight wins over auto-stop: the user asked for it.
    if (stopRequested) {
      finished = true
      callbacks.onStop(buildSummary('stopped'))
      return
    }

    const failures = settled.filter((r): r is PromiseRejectedResult => r.status === 'rejected')
    const lastFailure = failures.length > 0 ? failures[failures.length - 1] : undefined
    if (config.maxConsecErrors > 0 && consecErrors >= config.maxConsecErrors && lastFailure) {
      finished = true
      clear()
      const reason = `Auto-stopped: ${consecErrors} consecutive errors. Last: ${messageOf(
        lastFailure.reason
      )}`
      callbacks.onError(buildSummary('error'), reason)
      return
    }

    callbacks.onTick(sent, [...errors], consecErrors, Date.now() - startedAt)
  }

  return {
    start(runConfig, identity, runCallbacks) {
      config = runConfig
      callbacks = runCallbacks
      valueLists = useValueListStore.getState().snapshot()
      runId = identity.runId
      correlationId = identity.correlationId
      startedAt = Date.now()
      nextMessageId = 1
      sent = 0
      consecErrors = 0
      errors.length = 0
      finished = false
      inFlight = false
      stopRequested = false

      // First fan-out immediately, then every second — a duration of N seconds
      // gets exactly N productive ticks (§7.1). The tick promise is never
      // fire-and-forget: anything escaping tick() terminates the run through
      // onError — an unobserved rejection would leave the run stuck in RUNNING.
      const runTick = () =>
        tick().catch((error: unknown) => {
          if (finished) {
            // tick() only rejects after `finished` when a TERMINAL CALLBACK
            // threw (store settle, run-history write — e.g. a storage quota
            // error). The run's outcome may be unrecorded; that must be
            // reported, never dropped.
            console.error('Run terminal callback failed:', error)
            message.error(`Run finished but recording its outcome failed: ${messageOf(error)}`)
            return
          }
          finished = true
          clear()
          inFlight = false
          callbacks.onError(buildSummary('error'), `Engine tick failed: ${messageOf(error)}`)
        })
      runTick()
      timer = setInterval(runTick, TICK_MS)
    },

    stop() {
      if (finished || stopRequested) return
      clear() // no further ticks either way
      if (inFlight) {
        // Wait for the in-flight fan-out: its settle path reports STOPPED with
        // the acknowledged sends counted (decision 2026-07-18, option a).
        stopRequested = true
        return
      }
      finished = true
      callbacks.onStop(buildSummary('stopped'))
    },
  }
}
