/**
 * Zone D — Actions (feature §6.1, §5.5, §8).
 *
 * Preview resolves the working copy locally (no HTTP) at the chosen message
 * index, with a fresh runId/correlationId for display only, and shows the
 * resolved MessageRequest in a modal — with a warning banner when {{list:...}}
 * tokens reference missing/empty lists (they resolve to "").
 *
 * Start runs the same missing-list check as a pre-flight: a confirm
 * (Proceed / Cancel) warns but never blocks (§5.5). Start is enabled only in
 * idle with a target selected; Stop only while running. Terminal states are
 * exited via the Zone E summary card's "New run" (§7.2), not here.
 *
 * Header values resolve their placeholders (§5.3), exactly as the engine does
 * per message; the missing-list scan covers payload AND header values.
 */
import { useState } from 'react'
import { Alert, Button, InputNumber, Modal, Space } from 'antd'
import { findMissingLists, resolveString, resolveTemplate } from '../../engine/templateResolver'
import { useValueListStore } from '../../stores/valueListStore'
import type { MessageTemplate, RunStatus } from '../../types/generator'
import type { MessageRequest } from '../../types/queue'

interface GeneratorActionsProps {
  template: MessageTemplate
  status: RunStatus
  targetSelected: boolean
  previewIndex: number
  onPreviewIndexChange: (index: number) => void
  onStart: () => void
  onStop: () => void
  /** Opens the schedule modal (SCH.4); enabled under the same conditions as Start. */
  onSchedule: () => void
}

interface PreviewState {
  request: MessageRequest
  missingLists: string[]
}

export default function GeneratorActions({
  template,
  status,
  targetSelected,
  previewIndex,
  onPreviewIndexChange,
  onStart,
  onStop,
  onSchedule,
}: GeneratorActionsProps) {
  const [preview, setPreview] = useState<PreviewState | null>(null)
  const [previewError, setPreviewError] = useState<string | null>(null)

  /** Payload plus all header values — the full token surface for the list scan. */
  function scanSurface(): string {
    return [template.payloadSchema, ...Object.values(template.headers)].join('\n')
  }

  function buildPreview() {
    const valueLists = useValueListStore.getState().snapshot()
    // Fresh identity for DISPLAY only (§6.1 Zone D) — the real run identity is
    // generated by generatorStore.startRun() and passed to the engine.
    const context = {
      messageId: previewIndex,
      index: previewIndex - 1,
      runId: crypto.randomUUID(),
      correlationId: crypto.randomUUID(),
      now: new Date(),
      valueLists,
    }
    try {
      const payload = resolveTemplate(template.payloadSchema, context)
      const headers = Object.fromEntries(
        Object.entries(template.headers).map(([key, headerValue]) => [
          key,
          resolveString(headerValue, context),
        ])
      )
      setPreviewError(null)
      setPreview({
        request: {
          payload,
          headers,
          messageType: template.messageType,
          correlationId: context.correlationId,
          priority: template.priority,
          delaySeconds: template.delaySeconds,
          messageGroup: template.messageGroup,
        },
        missingLists: findMissingLists(scanSurface(), valueLists),
      })
    } catch (error) {
      setPreview(null)
      setPreviewError(error instanceof Error ? error.message : String(error))
    }
  }

  function startWithPreflight() {
    const valueLists = useValueListStore.getState().snapshot()
    const missing = findMissingLists(scanSurface(), valueLists)
    if (missing.length === 0) {
      onStart()
      return
    }
    Modal.confirm({
      title: 'Missing value lists',
      content: `These lists are missing or empty and will resolve to "": ${missing.join(', ')}. Proceed anyway?`,
      okText: 'Proceed',
      onOk: onStart,
    })
  }

  return (
    <div data-testid="generator-actions">
      <Space wrap>
        <label htmlFor="generator-preview-index">Preview message #</label>
        <InputNumber
          id="generator-preview-index"
          min={1}
          value={previewIndex}
          onChange={(v) => {
            if (v !== null) onPreviewIndexChange(v)
          }}
          style={{ width: 120 }}
        />
        <Button onClick={buildPreview}>Preview</Button>
        <Button type="primary" disabled={status !== 'idle' || !targetSelected} onClick={startWithPreflight}>
          Start
        </Button>
        <Button danger disabled={status !== 'running'} onClick={onStop}>
          Stop
        </Button>
        <Button disabled={status !== 'idle' || !targetSelected} onClick={onSchedule}>
          Schedule…
        </Button>
      </Space>

      {previewError && (
        <div data-testid="preview-error" style={{ marginTop: 12 }}>
          <Alert type="error" showIcon message={`Template does not resolve to valid JSON: ${previewError}`} />
        </div>
      )}

      <Modal
        title="Message preview"
        open={preview !== null}
        onCancel={() => setPreview(null)}
        footer={[
          <Button key="close" onClick={() => setPreview(null)}>
            Close
          </Button>,
        ]}
        width={640}
      >
        {preview && (
          <div data-testid="preview-modal">
            {preview.missingLists.length > 0 && (
              <div data-testid="missing-lists-warning" style={{ marginBottom: 12 }}>
                <Alert
                  type="warning"
                  showIcon
                  message={`Missing or empty value lists (resolved to ""): ${preview.missingLists.join(', ')}`}
                />
              </div>
            )}
            <pre style={{ maxHeight: 400, overflow: 'auto' }}>
              {JSON.stringify(preview.request, null, 2)}
            </pre>
          </div>
        )}
      </Modal>
    </div>
  )
}
